profile:
  name: dev

server:
  shutdown: graceful
  port: 8081
  servlet:
    session:
      timeout: 3600s

spring:
  session:
    store-type: redis
    redis:
      flush-mode: immediate
      serializer:
        session:
          json:
            enabled: true
  data:
    redis:
      host: localhost
      port: 6379
      password:
  datasource:
    url: jdbc:mysql://localhost:3306/payment
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    enabled: false

toss:
  payment:
    secret-key:
    base-url: https://api.tosspayments.com/v1/payments
    confirm-endpoint: /confirm
    read-timeout: 5000
    connection-timeout: 3000
